# Generated by Django 2.2.2 on 2019-06-23 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20190623_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centerinfo',
            name='Register_DateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 23, 14, 0, 59, 138599)),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='Register_DateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 23, 14, 0, 59, 138599)),
        ),
    ]
