# Generated by Django 2.2.2 on 2019-06-23 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_auto_20190623_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerinfo',
            name='Updated_DateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='centerinfo',
            name='Register_DateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='centerinfo',
            name='Use_Flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='Register_DateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 23, 23, 52, 44, 112097)),
        ),
    ]
