# Generated by Django 2.2.2 on 2019-06-25 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_auto_20190625_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='Register_DateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 25, 22, 30, 38, 399198)),
        ),
    ]
