# Generated by Django 2.2.2 on 2019-07-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_auto_20190624_1447'),
        ('WebApp', '0007_auto_20190625_2230'),
    ]

    operations = [
    ]
