# Generated by Django 2.2.2 on 2019-07-01 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_merge_20190701_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='Register_DateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 1, 15, 10, 48, 461078)),
        ),
    ]
